version: '3.7'

services:

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test@123
      - MYSQL_DATABASE=video-service
    ports:
      - 3306:3306
    command: --init-file /data/application/database-init.sql       
    volumes:
      - ../development/database-init.sql:/data/application/database-init.sql
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1